### ISSUE TITLE
component: pop-over

### ISSUE THREAD

**Issue by devCrossNet** [vuesion/vuesion#172]
something like this:
<img width="357" alt="screen shot 2018-06-22 at 13 51 31" src="https://user-images.githubusercontent.com/1667598/41775225-6512ac6c-7623-11e8-873c-72df18ffed40.png">

**Comment by ooxaam** [comment]
Hi, I would like to work on it. Can you kindly elucidate it a bit more.

Cheers :+1:

**Comment by devCrossNet** [comment]
@ooxaam If you want you can also use the next branch as the base branch and I will add this feature to the 1.4.0 milestone. I think it's better to have another release before version 2.0.0

**Comment by ooxaam** [comment]
Thanks, I'll follow the instructions :)

**Comment by Davidcreador** [comment]
I want to work on this one? Is @ooxaam still working on this?

**Comment by devCrossNet** [comment]
@Davidcreador I think you should go for it 👍

**Comment by livgrhm** [comment]
@devCrossNet did this ever get worked on? ;)

**Comment by devCrossNet** [comment]
@livgrhm nope, you can take it 😊

**Comment by einfalles** [comment]
👋 could we make a variant of the tooltip? i also see how iOS calls it a popover. i think in that case we can make it some sort of variation or composition with the dropdown menu. what do you think?

**Comment by devCrossNet** [comment]
@einfalles I think we need to architect the tooltip so that we can re-use it for the pop-over, you're completely right. I am not so sure about the dropdown, tho. Let's see how you imagine it and we can figure out the composition later 👍
