### ISSUE TITLE
component: rating

### ISSUE THREAD

**Issue by maunoxyd** [vuesion/vuesion#192]
## Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

## Desired functionality.
Would be nice to have a rating component like https://jsfiddle.net/craig_h_411/992o7cq5/

**Comment by livgrhm** [comment]
@devCrossNet working on it 👍

**Comment by devCrossNet** [comment]
merged to next
