### ISSUE TITLE
discussion: vision

### ISSUE THREAD

**Issue by devCrossNet** [vuesion/vuesion#317]
assets we have to keep:
- access to the critical code (UI, moving parts) to enable quick changes for devs
- opinionated
- 100% customizable
- Typescript
- ALL THE USE CASES !!! 😊

**Comment by tamer-mohamed** [comment]
These are good points to start with. I suggest labelling the main pillars that we want to improve. 
Developers want to be able to customise their projects, on the other hand, they don't want to worry about updating the infrastructure  (i.e build, bundle, manage webpack and its loaders ... etc.) 

I would like to highlight a few points which may help to achieve the points you mentioned above:
- Vue-starter as an npm package
     - Initialise the dev server
     - Bundle and build the app
     - Setup the client and server entry files 
     - Setup the state management and ability to hook into new modules
- 100% customizable
We should provide sort of default configurations that are able to be customized, these configurations are hooked into the build lifecycle 
- Examples 
 We should provide `examples` directory  in this repo that shows how to integrate `Vue-starter` with other libraries (i.e. passport.js and material design)

**Comment by tamer-mohamed** [comment]
Make sense, good thinking!

**Comment by devCrossNet** [comment]
@tamer-mohamed I already started yesterday to work on the service and I already migrated the following npm tasks:

- test
- extract -i18n-messages
- generate
- clean
- update
- e2e
- storybook

I will work on `dev` and `build` today. Hopefully, everything is done until Monday that I can show you the solution. There are a couple of topics where I need your input 😊 

here is the repo: https://github.com/devCrossNet/vue-starter-service. it's already set up that we can extend the mono-repo

**Comment by devCrossNet** [comment]
@tamer-mohamed it's already working:
https://github.com/devCrossNet/vue-starter/commit/cff70d0ccba9268f4bc4b974aeb6fa7662d8ac64

**Comment by SilverLeaves** [comment]
# My Vision

Although I translated the document into Chinese, but I have never used this project in my project.  

> The project is good, there is no problem,
> I am not strong enough to use it in my project, this is the problem

**I feel so sad!**

**Comment by devCrossNet** [comment]
@SilverLeaves let me know what we can do better. Is it too difficult or is something missing? What are the reasons you can not use it?

**Comment by SilverLeaves** [comment]
### Summary
There are serveral problems for me, maybe for others.
1. About myself
2. About tamplate

####  About myself (Maybe you should ignore this part)
Once I was a C++ programmer, I tended to use TS.
But in fact, I'm new to the front and back end. I'm not familiar with the front and back end and TS, so actually I use JS to write my project.
I'm trying ts. I need some time.

#### About tamplate
Here are two admin templates(relative to the vue-starter, they look like  framework) that I use(write by js):
1. [iview-admin](https://github.com/iview/iview-admin) 
![](https://img.shields.io/github/stars/iview/iview-admin.svg)
2. [vue-element-admin](https://github.com/PanJiaChen/vue-element-admin) 
![](https://img.shields.io/github/stars/PanJiaChen/vue-element-admin.svg)

I need time to turn vue-starter into a tamplate like [iview-admin](https://github.com/iview/iview-admin) or  [vue-element-admin](https://github.com/PanJiaChen/vue-element-admin) .
I will make efforts in this area.

**Comment by SilverLeaves** [comment]
tree、tree-table、uploader, this three components is very useful for me.
I will make efforts in this area, I need some time.

**Comment by SilverLeaves** [comment]
@devCrossNet 
Should I delete my comments? It doesn't seem to make any sense.

**Comment by devCrossNet** [comment]
No, it’s fine 👍🙂

**Comment by devCrossNet** [comment]
I created a new org: https://github.com/vuesion. If it's a good fit we have to think about a migration path for the vue-starter.

my current thinking is:
- create npm org as well
- move `vue-starter-packages` to `vuesion/vuesion`
- change packages to `@vuesion/[package-name]`
- replace vue-starter-packages in the vue-starter project
- move `vue-starter` repo to `vuesion/starter`
- update heroku, slack, etc
- (maybe) create twitter account
- ...

did I miss anything?

cc: @tamer-mohamed, @hugomn

**Comment by SilverLeaves** [comment]
@devCrossNet if you creat a twitter account ,maybe a [weibo微博](https://weibo.com/) account you should have one too

**Comment by devCrossNet** [comment]
@SilverLeaves that is a great idea. is it possible to use the side in English? and how would people respond if I would maintain the account in English?

**Comment by SilverLeaves** [comment]
with this app: weibo international. 
scan the QR code
![default](https://user-images.githubusercontent.com/31165554/53077153-5dcc1600-352c-11e9-8a91-2c6487f7f681.png)

![default](https://user-images.githubusercontent.com/31165554/53076959-ed24f980-352b-11e9-8219-9bc34ff5952a.png)

**Comment by SilverLeaves** [comment]
@devCrossNet Sorry, I make some mistake, Although Weibo is China's twritter, but china's developers usually communicate with each other through wechat.

**Comment by devCrossNet** [comment]
I heard a lot about wechat, will have a look 👍

**Comment by devCrossNet** [comment]
status update:

- [x] create github org
- [x] create npm org
- [x] move vue-starter-packages to `vuesion/packages`
- [x] change packages to `@vuesion/[package-name]`
- [x] replace vue-starter-packages in the vue-starter project
- [x] save heroku domain
- [x] create twitter account
- [ ] get a nice logo
- [ ] rebranding
- [ ] rename slack or switch to discord
- [ ] move vue-starter repo to `vuesion/vuesion`

**Comment by devCrossNet** [comment]
done! 🎉
