### ISSUE TITLE
Enable reactivity for vuex store in update operations

### ISSUE THREAD

**Issue by tamer-mohamed** [vuesion/vuesion#342]
**Is your feature request related to a problem? Please describe.**
Currently, update array or object in vuex store is not reactive.

**Describe the solution you'd like**
we need to use `Vue.set` to enable reactivity

@see https://github.com/vuejs/vuex/issues/1311#issuecomment-397867058

**Comment by tamer-mohamed** [comment]
@devCrossNet Would your opinion on that, is it intended?

**Comment by devCrossNet** [comment]
I never had a problem with it, you?

**Comment by tamer-mohamed** [comment]
we use computed props to with vuex getters, without enabling reactivity we would need to do manual effort to keep the state in sync.

To enable reactivity we need to follow one of this rules: https://vuex.vuejs.org/guide/mutations.html#mutations-follow-vue-s-reactivity-rules

**Comment by devCrossNet** [comment]
let's discuss on Monday. I did not experience issues so far with array operations. would be nice to see a use-case.

as far as I know, it's only important to use `Vue.set` to add new reactive properties that are not already in the initial state, data or computed.

**Comment by devCrossNet** [comment]
can this be closed?

**Comment by tamer-mohamed** [comment]
This is still valid. Changing the nested objects in vuex store, doesn't re-render the component (not reactive). 
https://vuejs.org/v2/guide/list.html#Caveats

However, I don't see that we deal with any nested objects or array in vuesion (was only at interstellar), hence this can be closed.

**Comment by devCrossNet** [comment]
ok, and what could be an action item for this?

**Comment by tamer-mohamed** [comment]
Are there any places we handle nested objects or arrays in vuex store in vuesion? 
otherwise, we close this ticket.

**Comment by devCrossNet** [comment]
We don’t have it, but what do you think about some docs around common things people should know before using vuesion?

**Comment by tamer-mohamed** [comment]
I like the idea. we could make FAQ or caveats section.
I just feel that this particular issue is more related to vuex not to vuesion, what do you think?

**Comment by devCrossNet** [comment]
Exactly what I thought 👍
