### ISSUE TITLE
How can I build this project in production mode?

### ISSUE THREAD

**Issue by majidln** [vuesion/vuesion#379]
How can I build this project in production mode?
I clone project and run npm install. after that, I run 'npm run build:spa'. so I open index.html at dist folder in a browser and there is some issue in console and browser screen is white.

<img width="516" alt="Screen Shot 2019-03-30 at 6 34 14 PM" src="https://user-images.githubusercontent.com/8521168/55277145-9eccfc80-531a-11e9-93c2-ee34ac17e58d.png">

**Comment by devCrossNet** [comment]
Here is the documentation: https://vue-starter.herokuapp.com/docs/guide/deployment.html#static-single-page-application

**Comment by devCrossNet** [comment]
@majidln can I close this issue?

**Comment by MohitTilwani15** [comment]
@majidln Looking at your console errors looks you are trying to load index.html locally and that would not work as you need to host it. To check locally, you can use python SimpleHTTPServer module. Just run` python -m SimpleHTTPServer` from dist directory and that would give you information about the port at which the files are being hosted and then you can check.

@devCrossNet After the build the SPA and host over python's SimpleHTTPServer module, there is still some error. As per the console the error is in vendors file 😅Will let you know if I found some info on it.

<img width="1127" alt="Screen Shot 2019-04-03 at 20 03 13" src="https://user-images.githubusercontent.com/13518712/55501865-a3abec00-564b-11e9-98d7-f6b1d6b2f1c1.png">

**Comment by devCrossNet** [comment]
@MohitTilwani15 have a look at the `Support` section in the docs: https://vue-starter.herokuapp.com/docs/guide/deployment.html#static-single-page-application

if it's not the appConfig issue, then we got something new

**Comment by devCrossNet** [comment]
can this be closed? @majidln

**Comment by devCrossNet** [comment]
inactive
