### ISSUE TITLE
aliases

### ISSUE THREAD

**Issue by eli007s** [vuesion/vuesion#390]
can we have something similar to:

https://github.com/chrisvfritz/vue-enterprise-boilerplate/blob/master/aliases.config.js

the use of aliases like '@shared' that would point to '@app/src/app/shared'

**Comment by devCrossNet** [comment]
I will have a look at it 👍 but in the meantime you can maintain your own aliases in the .vuesion/webpack.config.js

**Comment by devCrossNet** [comment]
@eli007s in the next version you will be able to do this in the `.vuesion/config.json`

```
{
  ...
  "webpack": {
    "aliases": {
      "@": "src",
      "@shared": "src/app/shared",
      "@components": "src/app/shared/components",
      "@static": "src/static"
    }
  }
}
```

**Comment by devCrossNet** [comment]
@eli007s you can start using it with `"@vuesion/service": "2.0.0-beta.1"`. just fyi

**Comment by eli007s** [comment]
woah, that was quick!

**Comment by eli007s** [comment]
@devCrossNet i tried this on version 2.0.0-beta.2 but it doesn't seem to work

i tested with line 137 in App.vue

`import VueIconVuesion from '@shared/components/icons/VueIconVuesion/VueIconVuesion.vue';`

**Comment by devCrossNet** [comment]
Sorry to hear that. I will check it again 👍

**Comment by devCrossNet** [comment]
@eli007s I just tried it out and it works. here is the PR: https://github.com/vuesion/vuesion/pull/393

important to know: the tsconfig file will be kept in sync with the vuesion config automatically. no need to maintain it manually.

**Comment by eli007s** [comment]
=) i love it
