### ISSUE TITLE
Link to 3rd party UI lib guide does not work in design system storybook

### ISSUE THREAD

**Issue by eipiminus1** [vuesion/vuesion#394]
In the Storybook describing the Design System 

https://vuesion.herokuapp.com/storybook/?path=/story/design-system-design-system--intro

there is a link that should take the reader to https://vuesion.herokuapp.com/docs/tutorials/third-party.html#vuetify

but it does not work, since it points to https://vuesion.herokuapp.com/docs/guide/third-party.html

**Comment by eipiminus1** [comment]
The link seems to be correct but for me it still does not behave correctly. I can right click "open in new tab" and go to the correct page. But a simple click only writes a message to console:
![image](https://user-images.githubusercontent.com/11791837/56948218-bd97fc00-6b2f-11e9-8fb6-9021741ef684.png)
I think this might have to do with vue router and the fact that `/docs` is outside of the `/storybook` app. But thats just wild guessing and I have no experience with vue-router.

**Comment by devCrossNet** [comment]
@eipiminus1 I will fix it in the next release, it's a problem with the markdown component. it replaces all links with a router-link. I'll find a workaround.
