### ISSUE TITLE
Is memory limit configurable?

### ISSUE THREAD

**Issue by sthielen** [vuesion/vuesion#397]
When I start vuesion, I get `Using 1 worker with 2048MB memory limit` in my logs. I am developing on an underpowered device, is there a CLI option that will let me drop this down to 1G?

**Comment by devCrossNet** [comment]
hey, there is no CLI option, but you can tweak your webpack config:

copy this into the file `.vuesion/webpack.config.js`
```
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');

/**
 * modify webpack config
 * @param {webpack.Configuration} config - webpack config
 * @param {string} target - build target, can  be "client" or "server"
 * @returns {*}
 */
module.exports = (config) => {
  config.performance = {
    hints: 'warning',
    maxAssetSize: 267000,
    maxEntrypointSize: 318000,
  };

  config.plugins[2] = new ForkTsCheckerWebpackPlugin({
    memoryLimit: 1024,
    vue: true,
  });

  return config;
};
```

here is the base config that is used in vuesion: https://github.com/vuesion/packages/blob/master/packages/service/src/webpack/config/base.ts

**Comment by sthielen** [comment]
Perfect, thank you!
