### ISSUE TITLE
npx @vuesion/service create my-app doesn't work

### ISSUE THREAD

**Issue by MohitTilwani15** [vuesion/vuesion#401]
**Describe the bug**
`npx @vuesion/service create my-app`  throws error Cannot find module 'vue-server-renderer'

**Expected behavior**
A folder with name my-app should be created with all the required dependencies being installed.

- Node - 11.14.0
- npm - 6.9.0

**Screenshots**
![Screen Shot 2019-04-28 at 20 29 20](https://user-images.githubusercontent.com/13518712/56868600-c9cb6e80-69f4-11e9-8f49-bdde0b803d54.png)

**Comment by devCrossNet** [comment]
Nice catch @MohitTilwani15 . We really need to get a better test suite in place for the cli. Thanks!
