### ISSUE TITLE
Value proposition 

### ISSUE THREAD

**Issue by devCrossNet** [vuesion/vuesion#407]
We want to collect things that make vuesion a good choice for developers and enterprises. Please reply with the features that you think make vuesion a great choice.

- server- side-rendering
- progressive web app
- static site generator
- i18n
- SEO
- design system
- storybook
- quick scaffolding and code generator
- enterprise ready
- testing, best practices and clean code
- real world use-cases

**Comment by derron1** [comment]
I think these for me personally makes vuesion stand out.

- Testing, best practices and clean code
- SEO
- Design System
- Static site generator
- Enterprise ready
- Quick scaffolding and code generator

**Comment by misikoff** [comment]
Vuesion doesn't feel like a 'black box' where magic happens. Everything is surfaced readily for exploration and understanding. This, coupled with Vuesion's implementation of best practices and best in class VueJS packages made Vuesion a great way to acclimate myself to enterprise VueJS development.

In addition to the great learning value, the qualities mentioned above enabled me to get moving quickly in my project, with the confidence that I would be comfortable scaling and adjusting things as I went.

**Comment by Akimotorakiyu** [comment]
- electron

there is a mystery - the browser of Government, hospital, financial institution, factory etc, only god know how to make compatibility.
