### ISSUE TITLE
generated storybook use components in templates with camelCase instead of kebab-case

### ISSUE THREAD

**Issue by ThePeach** [vuesion/vuesion#408]
**Describe the bug**
Generated storybook use components in templates with `camelCase` instead of `kebab-case`

**To Reproduce**
1. Generate a new component
2. open the related `.stories.ts` file
3. note the generated `template`

**Expected behavior**
the component should be written in `kebab-case`

**Actual behaviour**
it uses `camelCase`

**Additional context**
From https://github.com/vuesion/vuesion/blob/master/.vuesion/generators/component/component.stories.ts.hbs#L11 it seems clear some rejiggling needs to happen, unless this is exactly the expected behaviour.

**Comment by devCrossNet** [comment]
@ThePeach thanks for reporting. I totally missed that 😕 

in the meantime, you can change it locally. 
Change this line: https://github.com/vuesion/vuesion/blob/cf54dae0d45f418956aa9cf43a35776b4bdb2fa5/.vuesion/generators/component/component.stories.ts.hbs#L11

to this:`template:   `<{{ kebabCase componentName }}>{{ properCase componentName }}</{{ kebabCase componentName }}>`,`
