### ISSUE TITLE
opt out of storybook

### ISSUE THREAD

**Issue by eli007s** [vuesion/vuesion#414]
can we get an option to opt out of any storybook related files that get created or included by default on git pull?

great service, but not all of us use it and just have files we have to hunt for and delete =)

**Comment by devCrossNet** [comment]
Hey @eli007s,

it's not possible in the current version but I will take this as a feature request for a future major update.

In the meantime, you can run `find ./src -name "*.stories.*" -type f -delete` in the root directory of your project to delete all storybook related files.

**Comment by devCrossNet** [comment]
@eli007s you can also add `"./**/*.stories.ts"` to the `.vuesion/config.json`:

```
"clean": ["./dist", "./coverage", "./storybook-static", "./**/*.stories.ts"],
```

and run `npm run clean`

is this enough to close this issue or do you want to have a flag like `npx @vuesion/create my-app --no-storybook`?

**Comment by devCrossNet** [comment]
I'll close this issue, because storybook is a big part of the value proposition and it's easy enough to remove if somebody wants it.
