### ISSUE TITLE
Optimistic UI Updates or Caching strategy, worth it?

### ISSUE THREAD

**Issue by bernardocorbella** [vuesion/vuesion#415]
**Is your feature request related to a problem? Please describe.**
Not really. I'd like to implement Optimistic UI updates and I thought it's a good topic to cover with documentation or maybe add some extra support if we like.

**Describe the solution you'd like**
For example: I would like to load pages with the existing contents of the store and subsequently trigger an API request to patch those contents. This could be a practical scenario, but I'm aiming at something more general.

**Describe alternatives you've considered**
Continuing with the case above, an alternative would be to wait for API requests to finish before doing the route change. While this is a solid choice, sometimes you have certain resources that are unlikely to change in the span of a single session, so it's probably better to serve them from cache.

Again, this is just a practical scenario trying to illustrate the need to expand a bit more on caching.

**Additional context**
The goal of this issue is to discuss how these two concepts play into `vuesion`. Maybe writing a piece of documentation is enough.

Also, this library seems nice: https://github.com/superwf/vuex-cache

**Comment by devCrossNet** [comment]
@bernardocorbella sorry for not replying for so long. I will think about it over the weekend and give you some feedback 👍
