### ISSUE TITLE
Unhandled Promise Rejection Warning

### ISSUE THREAD

**Issue by lariguilger** [vuesion/vuesion#416]
I can't run the project, when I try run the command "npm run dev" I get the following error:
```
(node:7832) UnhandledPromiseRejectionWarning: #<Object>
(node:7832) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:7832) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: v3.2.0

**Comment by devCrossNet** [comment]
Hey @lariguilger,
thanks for reporting.

Is it a clean git checkout / freshly created project or did you already change/add code?

**Comment by lariguilger** [comment]
> 
> 
> Hey @lariguilger,
> thanks for reporting.
> 
> Is it a clean git checkout / freshly created project or did you already change/add code?

Yes, it's a freshly created project

**Comment by lariguilger** [comment]
Apparently, using "yarn run dev" works... No idea why.

**Comment by devCrossNet** [comment]
Strange! Which npm version do you have installed?

**Comment by lariguilger** [comment]
Node 10 and npm 6.4.1

**Comment by devCrossNet** [comment]
I have the same node version but my npm has the version `6.9.0`. can you update your npm (`npm i -g npm@6.9.0`) and tell me if the problem still exists?

**Comment by lariguilger** [comment]
> 
> 
> I have the same node version but my npm has the version `6.9.0`. can you update your npm (`npm i -g npm@6.9.0`) and tell me if the problem still exists?
I just tested it and nope, same problem still happens

**Comment by devCrossNet** [comment]
@lariguilger, sorry to hear that.

I will start investigating but it takes some time. I don't have a windows system running and I will be out of town this weekend.

If yarn solves your issue, I would be happy if you use it instead of npm until I fix it.

**Comment by JuanCarniglia** [comment]
Hey, having the same issue... any ideas?

**Comment by devCrossNet** [comment]
Please use yarn for now or a unix based system. I will investigate next week 👍

**Comment by devCrossNet** [comment]
@lariguilger, @JuanCarniglia 

please see: https://github.com/vuesion/vuesion/issues/423#issuecomment-520159263
