### ISSUE TITLE
error during rendering

### ISSUE THREAD

**Issue by zhanghanbing1998** [vuesion/vuesion#418]
### Hello, my English is not very good, but I would like to ask you to help me look at this problem, how can I solve it? I'm using vuesion for the first time. I'm looking forward to your answer. Thank you first.

error: error during rendering: /foo; error: {"stack":"Error: Error: Request failed with status code 404\n    at Store.eval (webpack-internal:///./src/app/foo/actions.ts:61:31)\n    at step (webpack-internal:///./src/app/foo/actions.ts:34:23)\n    at Object.eval [as throw] (webpack-internal:///./src/app/foo/actions.ts:15:53)\n    at rejected (webpack-internal:///./src/app/foo/actions.ts:7:65)\n    at process._tickCallback (internal/process/next_tick.js:68:7)","message":"Error: Request failed with status code 404"}

**Comment by devCrossNet** [comment]
Hello @zhanghanbing1998,

Can you tell me the steps on how to reproduce this error?

basically, it says that the URL you try to request from the `prefetch` function of your component doesn't exist. That means you have to either remove this request or make sure that the endpoint is available.

**Comment by zhanghanbing1998** [comment]
I'm sorry to reply to you now. I created the foo module based on the document. I used the `npm run generate` script and made an error when accessing http://localhost:3000/foo.

**Comment by devCrossNet** [comment]
@zhanghanbing1998 just to understand it correctly. You followed the guide in the documentation and this step: https://vuesion.github.io/docs/en/guide/cli.html#what-is-a-module did not work for you. Is that correct?

**Comment by zhanghanbing1998** [comment]
I found the reason, because this problem arose after deleting unnecessary code and files according to the document.[https://vuesion.github.io/docs/en/guide/clean-up.html](url)，after I clone the project again and try again, this problem does not arise. Finally, I want to ask you whether the redundant code deleted in the document is the dependency of creating the module.[https://vuesion.github.io/docs/en/guide/cli.html](url)

**Comment by devCrossNet** [comment]
@zhanghanbing1998 Ok, I understand it now.

The blueprints for the module and connected components are based on the `counter` module and as you deleted the counter route on the server side the newly generated module is not able to reach the API.

I might change the order of the guide to do the cleanup step after the module creation to avoid this confusion in the future. Do you think this would be enough?

**Comment by zhanghanbing1998** [comment]
Thank you. That's good. Thank you very much for answering my question. vuesion is very good. I spent a lot of time to solve SSR before. vuesion solved my problem better. Thank you for developing it. Finally, I wish you a good job!

**Comment by devCrossNet** [comment]
Thank you very much for your support @zhanghanbing1998 😊 

I'll let you know as soon as I made the changes to the docs.

**Comment by zhanghanbing1998** [comment]
hello,Johannes Werner,I have another question to ask you. I use the "vue-awesome-swiper" as a carousel plug-in, but this component relies on windows objects and document objects. However, when doing SSR, node does not have these objects, such as: window, document, how to solve this problem?

**Comment by devCrossNet** [comment]
Hey, you can use this trick: https://vuesion.github.io/docs/en/tutorials/third-party.html scroll to the bottom

**Comment by zhanghanbing1998** [comment]
Thank you. It's very useful.
