### ISSUE TITLE
Cant reach components page

### ISSUE THREAD

**Issue by ludo1960** [vuesion/vuesion#421]
Hello,
I've managed to install vuesion successfully but when I go to the components link i get a 404. In the terminal i see:
```
debug: whole request: 131ms
(node:2583) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limit
warn: unsupported route: /sw.js; error: {"code":404}
debug: whole request: 244ms
warn: unsupported route: /storybook/?path=%2Fstory%2Fatoms-badge--badge-variants; error: {"code":404}
debug: whole request: 229ms
warn: unsupported route: /sw.js; error: {"code":404}
```
How to fix this?

**Comment by devCrossNet** [comment]
Hey @ludo1960,

sorry for the late reply I just returned from vacation. The `/storybook` page is only available in the demo page (if you would run `npm run ci && npm start`). If you want to run storybook in dev mode use `npm run storybook:dev`.

Can you add your solution to ticket #420 to help others having the same issue?

**Comment by ludo1960** [comment]
npm run storybook:dev. does the trick, thanks for that!
