### ISSUE TITLE
Switch to eslint because Palantir is bad 

### ISSUE THREAD

**Issue by devCrossNet** [vuesion/vuesion#424]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by devCrossNet** [comment]
https://github.com/TypeStrong/fork-ts-checker-webpack-plugin#eslint

**Comment by Akimotorakiyu** [comment]
[@vue/eslint-config-prettier](https://www.npmjs.com/package/@vue/eslint-config-prettier)
[@vue/eslint-config-typescript](https://www.npmjs.com/package/@vue/eslint-config-typescript)

[eslint-plugin-prettier]()
[eslint-plugin-vue]()
