### ISSUE TITLE
JSON API package

### ISSUE THREAD

**Issue by ludo1960** [vuesion/vuesion#426]
Hello,

I am new to vuesion, but I see that it is a very well thought out package. I would like to consiume data from a json api source. I cannot find anything in the docs on how to go about this, I have read this [page](https://vuesion.github.io/docs/en/tutorials/prefetch-and-state-transfer.html) but it does not mention json api. Is there a package I could add to vuesion that would help me? Any other thoughts?

Thanks for all your hard work!

**Comment by devCrossNet** [comment]
Hey @ludo1960,

If you only need a json-file I would put it in the static folder and load it via axios.

If you mean a RESTful JSON API - vuesion is built on top of express so you can use any express best practices that you want. 

Examples can be found here: https://github.com/vuesion/vuesion/tree/master/src/server/routes

My Personal best practice is to not use the vuesion app as an API endpoint, I usually separate the API from the frontend.

Let me know if that helps.

**Comment by ludo1960** [comment]
Yeah it's restful Jason api that has a small number of end points. Forgive me if my question seems a bit dumb, but I am new to vue ijs. Should I just use express to grab the Jason data. I don't see how to do this in the links you sent. Just to be clear I have a headless drupal that serves up Jason api data. I'm just missing the bridge from the drupal Jason api to the vuesion package?


Sent from my iPhone

On 21 Jul 2019, at 15:34, Johannes Werner <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @ludo1960<https://github.com/ludo1960>,

If you only need a json-file I would put it in the static folder and load it via axios.

If you mean a RESTful JSON API - vuesion is built on top of express so you can use any express best practices that you want.

Examples can be found here: https://github.com/vuesion/vuesion/tree/master/src/server/routes

My Personal best practice is to not use the vuesion app as an API endpoint, I usually separate the API from the frontend.

Let me know if that helps.

**Comment by devCrossNet** [comment]
In this case, you can follow the example that you already mentioned. 

You may need to update the config: https://github.com/vuesion/vuesion/blob/master/src/app/config/default.json with your drupal api endpoint. 

And then you follow the typical vuex pattern (state, actions, mutations) and invoke the action in the `prefetch` method in one of the connected components.

Here is an example: https://github.com/vuesion/vuesion/blob/master/src/app/counter/Counter/Counter.vue#L56

The docs are pretty complete with this use-case. `How to fetch data from a remote API on the server side?` describes exactly your scenario, whereby `remote API` can be any kind of API (usually RESTFul)

**Comment by devCrossNet** [comment]
If you still have questions it might be better to talk in real-time in our Slack channel

**Comment by ludo1960** [comment]
Many thanks for taking the time to answer my question. I'll post back if I get it working.

Cheers

Sent from my iPhone

On 21 Jul 2019, at 18:00, Johannes Werner <notifications@github.com<mailto:notifications@github.com>> wrote:


If you still have questions it might be better to talk in real-time in our Slack channel

**Comment by devCrossNet** [comment]
@ludo1960 can this be closed?

**Comment by ludo1960** [comment]
Yes, thanks for all your help Johannes

Sent from my iPhone

On 5 Aug 2019, at 17:12, Johannes Werner <notifications@github.com<mailto:notifications@github.com>> wrote:


@ludo1960<https://github.com/ludo1960> can this be closed?
