### ISSUE TITLE
feat(i18n): add spanish translation

### ISSUE THREAD

**Issue by infrony** [vuesion/vuesion#428]
Achieve that the boilerplate can be used for projects in Spanish

**Comment by ludo1960** [comment]
google vue add language pack. vue i18n is already installed on vuesion, you just need to add the spanish language pack

**Comment by devCrossNet** [comment]
@infrony sorry, I missed this issue in my inbox somehow. Can you elaborate more on what you mean with this issue? 

I don’t know what has to be different in Spanish projects.

**Comment by devCrossNet** [comment]
@infrony can this be closed?

**Comment by infrony** [comment]
> @infrony can this be closed?

Yes @devCrossNet.
