### ISSUE TITLE
access global namespaces like document and window

### ISSUE THREAD

**Issue by eli007s** [vuesion/vuesion#429]
is there a way to get access to the windows and document object models?

or perhaps add a way to natively the "vuesion" way to access them . window.scrollX and window.location.

**Comment by devCrossNet** [comment]
Hey @eli007s,
you can access document and windows like you do it in every other vue application. the only thing you have to keep in mind is that these objects are not available on the server. so you either have to keep them out of the server-lifecycle or you surround it with `if(CLIENT){}`.

here is an example: https://github.com/vuesion/vuesion/blob/master/src/app/shared/components/VueModal/VueModal.vue#L93

**Comment by devCrossNet** [comment]
@eli007s can this be closed?
