### ISSUE TITLE
Use riteway for unit testing

### ISSUE THREAD

**Issue by tamer-mohamed** [vuesion/vuesion#430]
**Is your feature request related to a problem? Please describe.**
[There are 5 questions must be answered](https://medium.com/javascript-scene/what-every-unit-test-needs-f6cd34d9836d) by any unit test. 

```
What is the unit under test (module, function, class, whatever)?
What should it do? (Prose description)
What was the actual output?
What was the expected output?
How do you reproduce the failure?
```

When applications grow, it gets hard to make sure those questions are answered and many frameworks makes it easy to miss answering those questions.

**Describe the solution you'd like**
Eric Elliot built a frame around unit test best practices using [(riteway)](https://medium.com/javascript-scene/rethinking-unit-test-assertions-55f59358253f) which wrap [tape](https://github.com/substack/tape) framework by exposing a deep equality assertion only.

**Describe alternatives you've considered**
An Alternative would be to apply the best practices using jest, however this maybe hard to enforce it in large teams because of all the assertions jest provide could miss answering some of the [5 questions](https://medium.com/javascript-scene/what-every-unit-test-needs-f6cd34d9836d).

**Comment by devCrossNet** [comment]
looks pretty cool!

Can you create a branch and:
- set-up riteway (we can later integrate it in the vuesion/service)
- figure out if we have to use jest as runner + riteway or replace jest with riteway
- refactor a couple of tests in order to get a rough estimate what effort we have to plan in
?

Thanks @tamer-mohamed 👍

**Comment by devCrossNet** [comment]
related to #378

**Comment by tamer-mohamed** [comment]
Sure!

**Comment by devCrossNet** [comment]
@tamer-mohamed I want to integrate the testing-lib from kent. do you think this would make this issue obsolete?

**Comment by tamer-mohamed** [comment]
Nice! - yea this will make integrating RITEway with tape and react obsolete. 

However, would be good to wrap jest with RITEway approach, I see this will add the benefit of writing well-maintained tests.

Here is an example: https://github.com/janhesters/riteway-jest
