### ISSUE TITLE
Advance Forms

### ISSUE THREAD

**Issue by derron1** [vuesion/vuesion#435]
It would be great if we can add support for the follwing form types:
Switch
Range
Textfield
Switches

**Additional context**

<img width="649" alt="Screenshot 2019-08-19 at 16 29 33" src="https://user-images.githubusercontent.com/2568670/63278160-ac215e00-c29e-11e9-94d5-0b6e92f447d1.png">
<img width="653" alt="Screenshot 2019-08-19 at 16 28 19" src="https://user-images.githubusercontent.com/2568670/63278162-acb9f480-c29e-11e9-9dd7-aa5c6e875ffb.png">
<img width="171" alt="Screenshot 2019-08-19 at 15 40 06" src="https://user-images.githubusercontent.com/2568670/63278163-acb9f480-c29e-11e9-828b-760f9d0f1cf0.png">

**Comment by devCrossNet** [comment]
@derron1 we already have:
- [Switch/Toggle](https://vuesion.herokuapp.com/storybook/?path=/story/atoms-toggle--default)
- [Slider/Range](https://vuesion.herokuapp.com/storybook/?path=/story/atoms-slider--range)

The TextArea is missing but we can provide it in the next minor version.

**Comment by derron1** [comment]
> @derron1 we already have:
> 
>     * [Switch/Toggle](https://vuesion.herokuapp.com/storybook/?path=/story/atoms-toggle--default)
> 
>     * [Slider/Range](https://vuesion.herokuapp.com/storybook/?path=/story/atoms-slider--range)
> 
> 
> The TextArea is missing but we can provide it in the next minor version.

oh appologise ..If we can get Text area in on the next minor version thats great..

**Comment by derron1** [comment]
Could we also add a input dropdown form

**Comment by devCrossNet** [comment]
@derron1 do you mean the [select component](https://vuesion.herokuapp.com/storybook/?path=/story/atoms-select--default)?

In addition there is a [dropdown menu](https://vuesion.herokuapp.com/storybook/?path=/story/atoms-dropdownmenu--default) and an [auto complete](https://vuesion.herokuapp.com/storybook/?path=/story/organisms-autocomplete--default).

**Comment by derron1** [comment]
Yes I was reffering to the  select component sorry I didnt see it..Is there any resson why the styling is completly different to the defualt input.
I was checking the design system for something similar to this!!
![Screenshot 2019-08-23 at 00 36 50](https://user-images.githubusercontent.com/2568670/63556908-6e426500-c53e-11e9-879b-8bd357cfabe6.png)
![Screenshot 2019-08-23 at 00 37 21](https://user-images.githubusercontent.com/2568670/63556914-726e8280-c53e-11e9-840c-a34c41cc6aa1.png)

**Comment by devCrossNet** [comment]
The reason is that I prefer native components over fancy ones. They have less code, are accessible and work on every device.

If you want the material design system I recommend you to use vuetify.
