### ISSUE TITLE
Bug: Vuetify example doesn't work

### ISSUE THREAD

**Issue by danbars** [vuesion/vuesion#452]
**Describe the bug**
On a clean vuesion installation, following the instructions [here](https://vuesion.github.io/docs/en/tutorials/third-party.html#vuetify) - the compiler doesn't like this: `$vuetify.breakpoint.lgAndUp` in `App.vue`

Here's the stack trace:
```
error: error during rendering: /log/error; error: {"message":"Cannot read property 'lgAndUp' of undefined","stack":"TypeError: Cannot read property 'lgAndUp' of undefined\n    at Proxy.render (webpack-internal:///./node_modules/vue-loader/lib/loaders/templateLoader.js?!./node_modules/vue-loader/lib/index.js?!./src/app/app/App/App.vue?vue&type=template&id=414499ce&:20:50)\n    at VueComponent.Vue._render (webpack-internal:///./node_modules/vue/dist/vue.esm.js:3545:22)\n    at VueComponent.updateComponent (webpack-internal:///./node_modules/vue/dist/vue.esm.js:4063:21)\n    at Watcher.get (webpack-internal:///./node_modules/vue/dist/vue.esm.js:4476:25)\n    at new Watcher (webpack-internal:///./node_modules/vue/dist/vue.esm.js:4465:12)\n    at mountComponent (webpack-internal:///./node_modules/vue/dist/vue.esm.js:4070:3)\n    at VueComponent.Vue.$mount (webpack-internal:///./node_modules/vue/dist/vue.esm.js:9047:10)\n    at VueComponent.Vue.$mount (webpack-internal:///./node_modules/vue/dist/vue.esm.js:11941:16)\n    at init (webpack-internal:///./node_modules/vue/dist/vue.esm.js:3124:13)\n    at createComponent (webpack-internal:///./node_modules/vue/dist/vue.esm.js:5973:9)"}
```

Running on node 11.10.1

I think maybe vuetify has to be exported in app.ts, but I couldn't figure out exactly how.

**Comment by devCrossNet** [comment]
I think they had a major update. I will have a look at it. But be aware of the performance impact, the bundle size will increase to over 1MB with vuetify.

**Comment by danbars** [comment]
Thanks. They have the option to bundle modules selectively. Maybe it worth showing an example for that.

**Comment by devCrossNet** [comment]
Feel free to put this in the docs but I wouldn't spend more time on that topic. I will try to fix the current docs asap but optimizations are out of scope for me.

**Comment by devCrossNet** [comment]
@danbars guide is updated and deployed: https://vuesion.github.io/docs/en/tutorials/third-party.html
