### ISSUE TITLE
Failed the test "npm test"

### ISSUE THREAD

**Issue by ludo1960** [vuesion/vuesion#454]
Hi, 
changed a few bits and pieces ie site name and some routes. Running npm test results in the following. 

'Jest: "global" coverage threshold for statements (100%) not met: 99.91%
Jest: "global" coverage threshold for branches (100%) not met: 99.56%
Jest: "global" coverage threshold for lines (100%) not met: 99.91%

Summary of all failing tests
 FAIL  src/app/home/components/Stage/Stage.spec.ts
  ● Stage.vue › renders component

    expect(received).toBe(expected) // Object.is equality

    Expected: "vuesion"
    Received: "new-site"

      17 |     });
      18 | 
    > 19 |     expect(wrapper.find('h1').text()).toBe('vuesion');
         |                                       ^
      20 | 
      21 |     (wrapper as any).vm.$refs.stage.getClientRects = () => {
      22 |       return {

      at Object.<anonymous> (src/app/home/components/Stage/Stage.spec.ts:19:39)

 FAIL  src/app/home/Home/Home.spec.ts
  ● Home.vue › renders component

    expect(received).toHaveLength(expected)

    Expected length: 4
    Received length: 3
    Received object: {}

      30 | 
      31 |     expect(wrapper.findAll(Stage)).toHaveLength(1);
    > 32 |     expect(wrapper.findAll(HomeSection)).toHaveLength(4);
         |                                          ^
      33 |   });
      34 | });
      35 | 

      at Object.<anonymous> (src/app/home/Home/Home.spec.ts:32:42)

Test Suites: 2 failed, 69 passed, 71 total
Tests:       2 failed, 259 passed, 261 total
Snapshots:   0 total
Time:        81.544s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
'

Is there something in the manual I have missed, on what files can be edited?

**Comment by devCrossNet** [comment]
Hey @ludo1960,
you can edit any File. The tests are failing because you changed the component. Most of the times you have to change the tests, too (and this depends on the tests, what they asses and how they are written)

In this case, the test makes sure that the H1 is `vuesion` and that a certain amount of sections are present. It might not be the best test in the world but anyway you have to change your tests to fit the new component specs.

Of course, if you don't want to maintain or write tests you can:
- configure the test coverage to not have 100%
- remove the tests
- remove the test script from pre-commit hooks and CI system

Let me know if you need more information

**Comment by ludo1960** [comment]
OK Thanks Johan,
So I have made necessary changes and tests run ok now, next I tried https://vuesion.github.io/docs/en/guide/cli.html#create-a-module to make a module, not a connected module just a module. Running npm run dev churns out the default vuesion stuff and browsing to my new module /testmodule results in error, here is the log entry:

'{"level":"error","message":"error during rendering: /testmodule; error: {\"stack\":\"Error: Error: Request failed with status code 404\\n    at Store.eval (webpack-internal:///./src/app/testmodule/actions.ts:61:31)\\n    at step (webpack-internal:///./src/app/testmodule/actions.ts:34:23)\\n    at Object.eval [as throw] (webpack-internal:///./src/app/testmodule/actions.ts:15:53)\\n    at rejected (webpack-internal:///./src/app/testmodule/actions.ts:7:65)\\n    at processTicksAndRejections (internal/process/task_queues.js:85:5)\",\"message\":\"Error: Request failed with status code 404\"}"}
' 
What's wrong this time??

**Comment by devCrossNet** [comment]
it seems that it can not reach an API endpoint. usually, it tries to hit /increment. maybe, it's not available in your set up through a different api base url or you removed the demo-routes?

I would start troubleshooting here: https://github.com/vuesion/vuesion/blob/master/src/app/counter/actions.ts#L21 but in the actions file of your new module

**Comment by ludo1960** [comment]
OK I started by changing /src/app/config/default.json back to http://localhost:3000 from my **working** JSON api source. npm run dev works just fine, then my super douper new module from the now infamous npm run generate /testmodule:
'{"level":"error","message":"error during rendering: /testmodule; error: {\"stack\":\"Error: Error: Request failed with status code 404\\n    at Store.eval (webpack-internal:///./src/app/testmodule/actions.ts:61:31)\\n    at step (webpack-internal:///./src/app/testmodule/actions.ts:34:23)\\n    at Object.eval [as throw] (webpack-internal:///./src/app/testmodule/actions.ts:15:53)\\n    at rejected (webpack-internal:///./src/app/testmodule/actions.ts:7:65)\\n    at processTicksAndRejections (internal/process/task_queues.js:85:5)\",\"message\":\"Error: Request failed with status code 404\"}"}
'

**Comment by devCrossNet** [comment]
that means that the endpoint you try to request in the prefetch method of the connected component in that module is not available / returns 404.

**Comment by ludo1960** [comment]
So my bright shiny new module is still refering to:
```
      const res = await HttpService.put<ITestmoduleResponse>('/counter/increment', { count: state.count });
```
Why does the generator include unnecessary unwanted code? Is it a new regulation from Brussels? :)

**Comment by devCrossNet** [comment]
I am working on better templates. you can change the templates in the .vuesion folder by yourself if you want. the default template is the minimal setup to see the router, vuex, and vue working together. it's not intended to work in a changed vuesion environment - but as I said - I am working on a better solution.

**Comment by ludo1960** [comment]
wunderbar, danke johan!!
