### ISSUE TITLE
routes auto detected

### ISSUE THREAD

**Issue by eli007s** [vuesion/vuesion#456]
would it possible to have any `routes.ts` to be automatically detected and inserted into the spread operators in `router.ts`?

it would help in not forgetting to add a route.

**Comment by devCrossNet** [comment]
@eli007s can you elaborate more on the use case?

I assume that all components, modules and connected components are generated via the `npm run generate` command. In the case of creating a module it already automatically adds the `routes.ts` file of the module to the `router.ts` file

**Comment by eli007s** [comment]
-,- okay you win
