### ISSUE TITLE
where to store json api for vuex

### ISSUE THREAD

**Issue by ludo1960** [vuesion/vuesion#457]
Hello Johan,

In my never ending quest to get vuesion to "talk" to my JSON api endpoint. Following your advice and changing src/app/config/default.json and setting baseUrl to my JSON api endpoint results in the rest of the vuesion site to break down i.e. login/logout and the now famous increment leads to an error page. Changing baseUrl back to localhost:3000 makes everything work again. So I think the JSON api endpoint should go in the app/store.ts As there are a lot of other things going on in the app/store.ts I am unsure as how to procede?

**Comment by devCrossNet** [comment]
hey @ludo1960,

you have to understand the vuesion comes with initial scaffolding and that its main purpose is to demo different scenarios.

By changing the baseUrl you point all your api calls to your api-service. That means the service will not have the following endpoints included: 
- `/increment`
- `/decrement`
- `/token`
- `/protected`

That's the reason the following internal express routes are included in the demo:
- https://github.com/vuesion/vuesion/blob/master/src/server/routes/DemoRoutes.ts
- https://github.com/vuesion/vuesion/blob/master/src/server/routes/CounterRoutes.ts

Since these endpoints are completely useless in production set-ups (counter-example) you have to either implement them in your api-service (which I don't recommend for the counter-example) or remove the requests in your vuesion application.

I hope that helps.

**Comment by ludo1960** [comment]
Johan,
So I have to emulate the code in src/server/routes/DemoRoutes: 
```
  app.get('*', (req: Request, res: Response, next: any) => {
    const host: string = req.headers.host || 'localhost:3000';
    const redirect: string = `https://${host}` + req.url;

    if (req.headers['x-forwarded-proto'] && req.headers['x-forwarded-proto'] !== 'https') {
      res.redirect(redirect);
    } else {
      next();
    }
  });
  app.use('/storybook', serve('../../storybook-static'));
  app.use('/docs', (req: Request, res: Response) => {
    res.status(301).redirect('https://vuesion.github.io/docs/en/');
  });
``
in src/server/routes/MyRoutes to :
```
  app.get('*', (req: Request, res: Response, next: any) => {
    const host: string = req.headers.host || 'myjsonsite.com';
    const redirect: string = `https://${host}` + req.url;

    if (req.headers['x-forwarded-proto'] && req.headers['x-forwarded-proto'] !== 'https') {
      res.redirect(redirect);
    } else {
      next();
    }
  });
  });
```
Then access my routes with HttpService? got an example?

cheers,
ludo..........

**Comment by devCrossNet** [comment]
What i am saying is that the demo code is not supposed to work in a derived setup. Remove all the demo code an replace it with your actual business logic.

**Comment by ludo1960** [comment]
My business logic is to get vuesion to serve up my json endpoints. Is the code on the tracks
```
//MyRoutes.ts
  app.get('*', (req: Request, res: Response, next: any) => {
    const host: string = req.headers.host || 'myjsonsite.com/api';
    const redirect: string = `https://${host}` + req.url;

    if (req.headers['x-forwarded-proto'] && req.headers['x-forwarded-proto'] !== 'https') {
      res.redirect(redirect);
    } else {
      next();
    }
  });
```
If this is correct then I can use HttpService to grab the json data, I need an example of that

**Comment by devCrossNet** [comment]
you don't need this code. As you can read in the comment in the code it's only for heroku deployments: https://github.com/vuesion/vuesion/blob/master/src/server/routes/DemoRoutes.ts#L10

Did you ever read this: https://vuesion.github.io/docs/en/guide/clean-up.html#clean-up? Maybe, you can follow along with it. 

There are also TODO: comments in the code when parts are only for demo purposes. you should read more of the docs and the code comments.

**Comment by ludo1960** [comment]
Yes I have read the docs and completed the clean up, I tried to edit the templates to get rid of our good friend increment etc. Only trouble is I deleted something I shouldn't of and the plan went to pot. Fresh download, did clean up again as per the docs. Changed app/config/default.jason to "baseUrl": "http://opena.com/api"  then edited .vuesion/config.json  "outputDirectory": "./src/app/modules", then npm generate ....module venture ... added routes and vuex changed the app/src/router import { VentureRoutes } from './venture/routes'; to import { VentureRoutes } from './modules/venture/routes'; added your api call to /src/app/module/venture/action.ts, the endpoint i am after is http://opena.com/api/node/page?data.id=97ca30f4-0022-4b61-bee3-96452ed631d2
so as a start I edited to 
```
  async fetchVentures({ commit }): Promise<any> {
    try {
      const response = await HttpService.get<IVenture[]>('/node/page');
      commit('SET_VENTURES', response.data);
    } catch (e) {
      throw e;
    }
  }, 
```
Then in my Venture,vue i added :
```
          <vue-headline level="3">Data is {{ SET_VENTURES }}</vue-headline>
```
In logs I see
```
{"level":"error","message":"error during rendering: /venture; error: {\"stack\":\"Error: [vuex] expects string as the type, but found undefined.\\n    at assert (/var/vue/vuesion2/node_modules/vuex/dist/vuex.common.js:92:27)\\n    at unifyObjectStyle (/var/vue/vuesion2/node_modules/vuex/dist/vuex.common.js:795:5)\\n    at Store.dispatch (/var/vue/vuesion2/node_modules/vuex/dist/vuex.common.js:413:13)\\n    at Store.boundDispatch [as dispatch] (/var/vue/vuesion2/node_modules/vuex/dist/vuex.common.js:333:21)\\n    at Object.prefetch (webpack-internal:///./node_modules/ts-loader/index.js?!./node_modules/vue-loader/lib/index.js?!./src/app/modules/venture/Venture/Venture.vue?vue&type=script&lang=ts&:51:30)\\n    at eval (webpack-internal:///./src/server/isomorphic.ts:117:54)\\n    at Array.map (<anonymous>)\\n    at eval (webpack-internal:///./src/server/isomorphic.ts:115:76)\\n    at step (webpack-internal:///./src/server/isomorphic.ts:42:23)\\n    at Object.eval [as next] (webpack-internal:///./src/server/isomorphic.ts:23:53)\\n    at eval (webpack-internal:///./src/server/isomorphic.ts:17:71)\\n    at new Promise (<anonymous>)\\n    at __awaiter (webpack-internal:///./src/server/isomorphic.ts:13:12)\\n    at eval (webpack-internal:///./src/server/isomorphic.ts:99:45)\\n    at /var/vue/vuesion2/node_modules/vue-router/dist/vue-router.common.js:2003:11\\n    at Array.forEach (<anonymous>)\",\"message\":\"[vuex] expects string as the type, but found undefined.\"}"}
```

**Comment by devCrossNet** [comment]
same here, discussions should happen in slack.
