### ISSUE TITLE
`npx @vuesion/create foobar` fails on missing lodash

### ISSUE THREAD

**Issue by analytik** [vuesion/vuesion#460]
When I run `npx @vuesion/create` for the first time, I get an error. I suspect there are missing dependencies in the `create` package.

```λ npx @vuesion/create vuesion-blank
npx: installed 148 in 30.21s
Cannot find module 'lodash'
Require stack:
- C:\Users\someuser\AppData\Roaming\npm-cache\_npx\5884\node_modules\@vuesion\create\dist\create\src\commands\create.js
- C:\Users\someuser\AppData\Roaming\npm-cache\_npx\5884\node_modules\@vuesion\create\dist\create\src\index.js
- C:\Users\someuser\AppData\Roaming\npm-cache\_npx\5884\node_modules\@vuesion\create\bin\cli
```

Windows 10 x64, Node.js v12.9.1, npm 6.10.2

**Comment by devCrossNet** [comment]
@analytik I will have a look into it. Thanks for reporting. in the meantime you can use git clone to get a local copy.

**Comment by devCrossNet** [comment]
@analytik it should work now. I only tested it on OSX but the bug was not OS-specific, so should work with windows, too.

Can you confirm?

**Comment by analytik** [comment]
```
λ npx @vuesion/create 1foobar
npx: installed 149 in 24.482s
✓ Project 1-foobar successfully created
```

Fixed, thanks!
