### ISSUE TITLE
component: color-picker

### ISSUE THREAD

**Issue by devCrossNet** [vuesion/vuesion#473]
typical color picker (like sketch or procreate)

1. step: simple hex web colors
2. step: rgba color picker
3. step: HSL color picker

**Comment by devCrossNet** [comment]
https://caniuse.com/#feat=input-color

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color

**Comment by Akimotorakiyu** [comment]
lab color picker may useful for get the same lightness of color in feeling.

**Comment by Akimotorakiyu** [comment]
mix-blend-mode and background-blend-mode preview maybe useful for design theme
