### ISSUE TITLE
How about work with electron 

### ISSUE THREAD

**Issue by Akimotorakiyu** [vuesion/vuesion#477]
desktop app, like [github desktop](https://github.com/desktop/desktop)

**Is your feature request related to a problem? Please describe.**
work with electron 

**Describe the solution you'd like**
work with electron 

**Describe alternatives you've considered**
work with electron 

**Additional context**
work with electron

**Comment by devCrossNet** [comment]
@Akimotorakiyu I have no experience with electron. do you need some help to get electron working with vuesion or does vuesion have to change something in order to work with electron?

**Comment by Akimotorakiyu** [comment]
Could integrate [vue-cli-plugin-electron-builder](https://nklayman.github.io/vue-cli-plugin-electron-builder/) into vuesion

That will make us create electron SPA app easily.
