### ISSUE TITLE
Page Protection

### ISSUE THREAD

**Issue by itgelo** [vuesion/vuesion#480]
If page `/` requiresAuth and user does not have a token redirect to `/login`, and if user has a token can not access the page `/login`.
how to handle this case in vuesion?

**Comment by devCrossNet** [comment]
@itgelo please, use slack or discord for discussions and questions.

The issue system should be used for bugs and feature requests.

Other than that it's no different in vuesion than from the official vue-router docs. There is even an example of a route guard in the demo code: https://github.com/vuesion/vuesion/blob/master/src/app/router.ts#L28 and https://github.com/vuesion/vuesion/blob/master/src/app/example/dashboard/routes.ts#L9

**Comment by itgelo** [comment]
i have a simple code
`src/app/signin/routes.ts`
```
export const SigninRoutes: RouteConfig[] = [
  {
    ...
    meta: {
      requiresNoAuth: true,
    },
    ...
  },
`];`
```
`src/app/router.ts`
```
router.beforeEach((to: Route, from: Route, next: any) => {
  const isAuthenticated = store.getters['signin/isAuthenticated'];

  if (!isAuthenticated && to.matched.some((record: RouteRecord) => record.meta.requiresAuth)) {
    next({ path: '/', query: { redirect: to.fullPath } });
  } else if (isAuthenticated && to.matched.some((record: RouteRecord) => record.meta.requiresNoAuth)) {
    next({ path: '/dashboard' });
  } else {
    next();
  }
});
```
in development environment when I'm logged in I can't access page `/`
but in production environment I can access pages `/` even though I have logged in. when I check page `/` the cookie is reset to null and I try to access the page `/dashboard` cookies are well preserved.

Persisting state
`src/app/store.ts`

```
...
import { SigninModule } from './signin/module';
...

export const store: Store<IState> = new Vuex.Store({
  state,
  plugins: [
    VuexPersist([
      new PersistCookieStorage(['app', 'signin'], {
        cookieOptions: {
          expires: 365,
        },
        beforePersist: beforePersistCookieStorage,
      }),
    ]),
  ],
});
...
registerModule('signin', SigninModule);
```

dev environment everything works fine, but not in prod environment
something is wrong with my code?

**Comment by devCrossNet** [comment]
@itgelo sorry that I get back to you so late. I was sick and forgot about this issue. Do you still have that issue? or can the issue be closed?

**Comment by devCrossNet** [comment]
I close this issue due to inactivity
