### ISSUE TITLE
components: re-design and re-write

### ISSUE THREAD

**Issue by devCrossNet** [vuesion/vuesion#487]
align all components with the new design system sketch file and rewrite all of them to use the composition API and the testing library

Components:
- Accordion
- Autocomplete
- Badge
- Breadcrumb
- ~~Button~~
- Calendar
- Card
- Carousel
- Checkbox
- Collapse
- CookieConsent
- DataTable
- DatePicker
- DateRangePicker
- DonutChart
- Dropdown
- Footer
- ~~Grid~~
- Headline
- Image
- ~~Input~~
- Markdown
- ~~Modal~~
- NavBar
- NavigationProgress
- NotificationStack
- Pagination
- Select
- Sidebar
- Slider
- Spinner
- StarRating
- TabGroup
- Textarea
- Toggle
- Tooltip
- Truncate

**Comment by Akimotorakiyu** [comment]
tailwindcss https://tailwindcss.com/

**Comment by devCrossNet** [comment]
@Akimotorakiyu can you tell me a little bit about your experience with tailwind? I am really not convienced about this approach.
