### ISSUE TITLE
npm run dev getting error

### ISSUE THREAD

**Issue by fademan01** [vuesion/vuesion#497]
**Describe the bug**
I follow the steps for starter, try to run npm run dev command then met the error without any clues to figure out

 `
 vuesion@3.7.2 dev /home/khai/store/vuesion
vuesion dev -o

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vuesion@3.7.2 dev: `vuesion dev -o`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vuesion@3.7.2 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/khai/.npm/_logs/2020-03-04T06_35_07_848Z-debug.log
`

debug log
`0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dev' ]
2 info using npm@6.14.1
3 info using node@v10.19.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle vuesion@3.7.2~predev: vuesion@3.7.2
6 info lifecycle vuesion@3.7.2~dev: vuesion@3.7.2
7 verbose lifecycle vuesion@3.7.2~dev: unsafe-perm in lifecycle true
8 verbose lifecycle vuesion@3.7.2~dev: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/khai/store/vuesion/node_modules/.bin:/home/khai/gems/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle vuesion@3.7.2~dev: CWD: /home/khai/store/vuesion
10 silly lifecycle vuesion@3.7.2~dev: Args: [ '-c', 'vuesion dev -o' ]
11 silly lifecycle vuesion@3.7.2~dev: Returned: code: 1  signal: null
12 info lifecycle vuesion@3.7.2~dev: Failed to exec dev script
13 verbose stack Error: vuesion@3.7.2 dev: `vuesion dev -o`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid vuesion@3.7.2
15 verbose cwd /home/khai/store/vuesion
16 verbose Linux 4.15.0-88-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
18 verbose node v10.19.0
19 verbose npm  v6.14.1
20 error code ELIFECYCLE
21 error errno 1
22 error vuesion@3.7.2 dev: `vuesion dev -o`
22 error Exit status 1
23 error Failed at the vuesion@3.7.2 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]`

**Comment by devCrossNet** [comment]
hey, which node/npm versions and operating system are you using?

To get more information you can run `vuesion dev --debug`.

**Comment by devCrossNet** [comment]
closed due to inactivity

**Comment by jerrychong25** [comment]
FYI. I encountered similar issue too, as per mentioned in https://github.com/vuesion/vuesion/issues/502

**Comment by sswam** [comment]
I have a similar issue, following the npx install instructions.
I did run `npm audit fix` before `npm run dev`

# node --version
v14.9.0
# uname -a
Linux debian 5.7.0-3-amd64 #1 SMP Debian 5.7.17-1 (2020-08-23) x86_64 GNU/Linux
# cat /etc/issue
Debian GNU/Linux bullseye/sid \n \l

**Comment by devCrossNet** [comment]
@sswam the current version on master is not tested with node versions above 10. if you want, you can try `npx @vuesion/create my-app --next` to get the RC for vuesion 4 which is tested with node version 12

**Comment by sswam** [comment]
Thanks @devCrossNet, the "next" version is working for me on node version 14.
