### ISSUE TITLE
Unable to npm run dev successfully

### ISSUE THREAD

**Issue by jerrychong25** [vuesion/vuesion#502]
**Describe the bug**
Unable to **npm run dev** successfully as per **Getting started** guide mentioned in https://github.com/vuesion/vuesion.

**To Reproduce**
- Download or clone (git clone https://github.com/vuesion/vuesion) the repository
- Change directory cd vuesion
- Install dependencies: npm install
- Run npm run dev

**Expected behavior**
Build and run project successfully.

**Logs**
```
jerrychong [14:41:56] [~/Desktop/vue-vuesion] [dev *]
-> % npm run dev

> vuesion@3.7.2 dev /Users/jerry/Desktop/vue-vuesion
> vuesion dev -o

Start development mode...
Exit with error code: 1

Trace:
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vuesion@3.7.2 dev: `vuesion dev -o`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vuesion@3.7.2 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jerry/.npm/_logs/2020-05-02T06_51_15_129Z-debug.log

jerrychong [14:51:15] [~/Desktop/vue-vuesion] [dev *]
-> % vuesion dev --debug .
zsh: command not found: vuesion
```

**Desktop (please complete the following information):**
 - OS: macOS v10.14.6
 - Browser: Firefox v75.0

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by jerrychong25** [comment]
Similar issue mentioned in https://github.com/vuesion/vuesion/issues/497

**Comment by devCrossNet** [comment]
hey @jerrychong25,
sorry for the late reply. Which version of node and npm do you use?

The current master only seems to work with node 10, not 12 or 13 (if you use `npx @vuesion/create my-app --next` you're able to use node 12+)

**Comment by jerrychong25** [comment]
Hi @devCrossNet ,

node version: v12.13.0
npm version: v6.14.4

**Comment by devCrossNet** [comment]
@jerrychong25 did you try to downgrade node to version 10 with a package like `n`or `nvm`? Or did you try `@vuesion/create my-app --next`?

**Comment by jerrychong25** [comment]
@devCrossNet 

Yes, `npx @vuesion/create my-app --next` command is working for Node 12+ in my case.

Thanks for your help.
