### ISSUE TITLE
complete color palette and define color variations

### ISSUE THREAD

**Issue by devCrossNet** [vuesion/vuesion#513]
file with namings of the current tokens: https://github.com/vuesion/vuesion/blob/next/src/assets/designSystem/themes/light.scss

decisions to make:
- how do we want to name the tokens
- how much color tints/shades do we need per color variation and how to name them
- experiment with variation-shade-naming (--brand-default-hover -> something else)
- rename shadows to elevation
- think about typo components, their purpose and naming

**Comment by devCrossNet** [comment]
Let's have a look at: https://github.com/diez/diez

**Comment by einfalles** [comment]
Meeting note

- Add in secondary colors
- Add in base text styles
- ...ideal every component use the text style
- Define general colors we want to use for various components or interactions
- ...states: hover, focus, select, activated
- What kind of spacings should we having? Define scale
