### ISSUE TITLE
lingering old guide, probably

### ISSUE THREAD

**Issue by twildeman** [vuesion/vuesion#537]
Hello there,

I was trying to install using this old guide: [https://vue-starter.herokuapp.com/docs/guide/install.html#via-npx](https://vue-starter.herokuapp.com/docs/guide/install.html#via-npx) 

But that didn't work, obviously.

I finally noticed, way longer than necessary, that I was looking at the wrong documentation.

So I think this old documentation can be removed.

**Comment by devCrossNet** [comment]
Thanks for letting me know. I need to take down the old project. it's basically only there to redirect to the new vuesion page. sorry for the inconvenience.

a small tip from my side. use `@vuesion/create my-app --next` to get the new version of vuesion which is not final yet but already used in production and is based on Nuxt.js. Deployment can be found here: vuesion-next.herokuapp.com

**Comment by twildeman** [comment]
Thanks for the tip. Will try that later. 

Shouldn't the argument be --nuxt?

**Comment by devCrossNet** [comment]
no, it's `--next` for "next-version" (it was --nuxt for a short time because I couldn't decide if vuesion should really switch to nuxt - but now it is decided)

**Comment by devCrossNet** [comment]
deleted the Heroku app.
