### ISSUE TITLE
security fixes

### ISSUE THREAD

**Issue by mmarabesi** [vuesion/vuesion#556]
Hello there, is any plan to update security dependencies for vuesion?

**Comment by devCrossNet** [comment]
hello @mmarabesi,

yes! I am working on a new version that will be released in the upcoming weeks. It's basically a rewrite based on Nuxt.js.
You can already try it (I use it in production already) You can find it here: https://github.com/vuesion/vuesion/tree/next
or you can run `npx @vuesion/create [project-name] --next`.

**Comment by mmarabesi** [comment]
Thanks for the quick response, will have a look at the next version then.
