### ISSUE TITLE
Update package.json

### ISSUE THREAD

**Issue by eramosr16** [vuesion/vuesion#569]
**Describe the bug**
Upgrade package.json dependencies to overcome vulnerabilities.

**To Reproduce**
1. npx @vuesion/create vsession --next
2. npm install

**Expected behavior**
0 vulnerabilities found

**Screenshots**
![image](https://user-images.githubusercontent.com/17813469/131205335-c0f151b6-c4c3-488d-b86c-7085ac5859e1.png)

**Comment by devCrossNet** [comment]
I will have a look into it. The last time I checked it wasn't anything that ended up in the production build.

**Comment by devCrossNet** [comment]
done in the next branch
