### ISSUE TITLE
sh: cross-env: command not found

### ISSUE THREAD

**Issue by rindibudiaramdhan** [vuesion/vuesion#584]
**Describe the bug**
Hello, I am new here. I got error when I follow steps from docs. It wont start.

**To Reproduce**
1. Run `npx @vuesion/create logistik-fe`
2. Run `cd logistik-fe`
3. Run `npm run dev`

**Expected behavior**
Vuesion Run in my local.

**Screenshots**
![image](https://user-images.githubusercontent.com/19951241/150141304-2e55b17b-25be-4b5b-a339-fa6f62c13b04.png)

**Desktop (please complete the following information):**
 - OS: masOS Monterey
 - Browser Google Chrome
 - Version 12.1

**Comment by rindibudiaramdhan** [comment]
I am at:
node -v : 17.4.0
npm -v : 8.3.1

**Comment by devCrossNet** [comment]
hey @rindibudiaramdhan,
can you check if all dependencies have been installed correctly?

maybe even remove the node_modules folder and run npm install again?

worst-case scenario: install cross-env globally with npm i -g cross-env

I didn't check the compatibility with node 17 yet. could be an issue, but I hope not.

**Comment by devCrossNet** [comment]
@rindibudiaramdhan can I close this issue?

**Comment by rindibudiaramdhan** [comment]
> hey @rindibudiaramdhan,
> can you check if all dependencies have been installed correctly?
> 
> maybe even remove the node_modules folder and run npm install again?
> 
> worst-case scenario: install cross-env globally with npm i -g cross-env
> 
> I didn't check the compatibility with node 17 yet. could be an issue, but I hope not.

ok ill try
