### ISSUE TITLE
Is the v5 milestone being actively developed?

### ISSUE THREAD

**Issue by danielduckworth** [vuesion/vuesion#605]
Hi, just wondering if Vuesion V5 is still an active project?

**Comment by devCrossNet** [comment]
Hey @danielduckworth!

Yes, the progress can be tracked here: https://github.com/vuesion/vuesion5

It's currently blocked by an issue with the latest RC and missing nuxt modules.
I hope that nuxt 3 will be ready by end of this year so I can finish it off, push it to the main repo and release it early next year.

Best,
Johannes

**Comment by devCrossNet** [comment]
it's now merged to the next branch in this repository and is almost feature complete. Release is coming soon!
