### ISSUE TITLE
spacing issues on the home page

### ISSUE THREAD

**Issue by dhaladitya108** [vuesion/vuesion#630]
**Describe the bug**

**To Reproduce**
1. Go to https://vuesion.herokuapp.com
2. Scroll down to 'Built for modern product teams section'
4. See badge spacing issue for table and moble screen sizes 

**Screenshots**
![Screenshot 2024-06-09 at 9 19 15 AM](https://github.com/vuesion/vuesion/assets/59838143/70eb252c-38e7-421e-911a-e1fb8324b051)

**Comment by dhaladitya108** [comment]
fix for this addressed in this pr: https://github.com/vuesion/vuesion/pull/631

**Comment by devCrossNet** [comment]
close this issue in favor of the new home page version
